package com.kata.trade_accounting.model;

public enum DocumentType {
    BUYER_ORDER,
    BUYER_INVOICES,
    SHIPMENT,
    SUPPLIER_ORDERS,
    SUPPLIER_INVOICES,
    ACCEPTANCE,
    INCOMING_PAYMENTS,
    RECEIPT_ORDERS,
    OUTGOING_PAYMENTS,
    DISBURSEMENT_ORDERS,
    INTERNAL_ORDERS,
    MOVEMENTS,
    INVENTORY,
    POSTING,
    WRITE_OFF,
    TECHNOLOGICAL_OPERATION,
    PRODUCTION_ORDER,
    PRODUCTION_TASK
}
