package com.kata.trade_accounting.model;

public enum PersonalProtectiveEquipmentName {
    FACE_MASK_FOR_RESPIRATORY_PROTECTION,
    GENERAL_PURPOSE_RESPIRATOR,
    SURGICAL_RESPIRATOR,
    NASAL_PROTECTION_AGENT,
    EXAMINATION_GLOVES,
    EXAMINATION_POLYISOPRENE_GLOVES,
    HYGIENIC_CLOTHES_SET,
    HYGIENIC_OVERALLS
}
